spring.application.name=pahal
# Tell Spring AI where your local Ollama engine is listening
spring.ai.ollama.base-url=http://localhost:11501

# Specify the exact AI model you want Ollama to run (e.g., llama3, mistral, deepseek-coder)
#spring.ai.ollama.chat.options.model=qwen2.5-coder:7b
spring.ai.ollama.chat.options.model=llama3.1:8b
LOG_FILE_PATH=C://logs//abcd